spring.datasource.url=jdbc:mysql://nutrition-db.cpoycimscei0.eu-north-1.rds.amazonaws.com:3306/nutritiondb
spring.datasource.username=admin
spring.datasource.password=Yash192005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true